fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    exception:
        enabled: true
        exception_controller: 'ApiBundle\Controller\ExceptionController::showAction'
    view:
        view_response_listener: true
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true